# Generated by Django 2.2.22 on 2024-05-06 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
 
        migrations.RemoveField(
            model_name='question',
            name='type_reponse',
        ),
        migrations.RemoveField(
            model_name='village',
            name='ID_Commune',
        ),
        migrations.RemoveField(
            model_name='village',
            name='ID_Moughata',
        ),
        migrations.AddField(
            model_name='question',
            name='categorie',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('choice', 'Choice'), ('composite', 'Composite'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reponse',
            name='response_date',
            field=models.DateField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='idCommit',
            field=models.ForeignKey(db_column='idCommit', default='', max_length=100, on_delete=django.db.models.deletion.CASCADE, to='myapp.Commune'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formilair',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='formilair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formilair', to='myapp.Formilair'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
